[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
lazy_static = "1.5.0"
tensor = { path = "../tensor" }
petgraph = "0.8.3"
tracing = "0.1.41"
tracing-chrome = "0.7.2"
tracing-subscriber = "0.3.18"
cudarc = { version = "0.17.3", features = ["cuda-12090"], optional = true }
rayon = { version = "1.11", optional = true }

[features]
default = ["cuda", "parallel"]
cuda = ["cudarc"]
parallel = ["rayon"]

[[bench]]
name = "cpu"
harness = false

[[bench]]
name = "gpu"
harness = false
required-features = ["cuda"]

[dev-dependencies]
criterion = "0.7.0"
rstest = "0.26.1"
test-log = "0.2.18"
